### ISSUE TITLE
Kind reminder

### ISSUE THREAD

**Issue by kakra** [gardotd426/dotfiles#1]
Just a kind reminder, you probably don't want to share this as it is, e.g. the chromium profile contains keys for Gmail...

**Comment by gardotd426** [comment]
Eek. Didn't even realize I'd made this. The dots haven't been updated in forever and the keys are no longer good, but I appreciate that and will remove that stuff. Thanks for looking out.

**Comment by kakra** [comment]
Deleting just some stuff doesn't remove anything from history. You can still access your old commits and see all the content. I suggest to just purge the complete repository here from github. If you actually need a dotfiles repo, you should recreate it from scratch, carefully selecting which dotfiles go in, and which don't.

I'm not a black hat or something but I'm sure there're people out there which already found this stuff by bots, or checked out your dotfiles and had valid logged in sessions and cookies in the browser. I can only wildly guess what else there might be in the vast pile of configuration data. Really, just kill it and start over, and maybe rotate your passwords. `.config`, `.local`, and `.cache` are particular directories you don't want to share unconditionally: They contain password storages, maybe clear-text passwords, cache entries that let people track down your activity and make you vulnerable to social engineering attacks.

There are a lot of articles out there that tell horrifying stories about secrets accidentally shared via Github, and how difficult it is to properly remove that and do the aftermath. Pull a local mirror to your PC, make a backup of it, kill it from Github. And then look at the damage that could have done and take the proper countermeasures.
